# Generated by Django 2.0.3 on 2018-03-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='file_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
